### ISSUE TITLE
Stopped working from 1.1.84

### ISSUE THREAD

**Issue by amd64fox** [ririxidev/spotifyEnableDevTools#1]
Does not work with the new version `1.1.84`

If you haven't received this version yet, you can download it [here](https://cutt.ly/8EH6NuH)

**Comment by rxri** [comment]
Added in https://github.com/ririxidev/spotifyEnableDevTools/commit/743264a775d81bb921c768da4489b9ce954387cb, will create release soon.

**Comment by ririxidev** [comment]
https://github.com/ririxidev/spotifyEnableDevTools/releases/tag/v1.1.0
